table CtxDept
	lineageTag: 349449cf-2c17-839b-7a71-8146d3485d32

	measure 'Dept share of units' = SUM(CtxDept[share_of_units])
		formatString: 0.0%
		lineageTag: 2721032f-d943-513b-d1d1-27ccf428796c

	measure 'Dept zero-sales share' = AVERAGE(CtxDept[zero_share_after_launch])
		formatString: 0%
		lineageTag: 40003a82-d272-9fd7-c7c3-5c3a27f4c0c3

	column cat_id
		dataType: string
		lineageTag: 5fa417ba-59ec-76e8-5291-50d21c167506
		summarizeBy: none
		sourceColumn: cat_id

		annotation SummarizationSetBy = User

	column dept_id
		dataType: string
		lineageTag: 2ae12a4a-be35-9f58-926a-3660eb4635af
		summarizeBy: none
		sourceColumn: dept_id

		annotation SummarizationSetBy = User

	column series
		dataType: int64
		formatString: 0
		lineageTag: 53b988df-fd6f-3cd9-d357-e6d30c499fcf
		summarizeBy: none
		sourceColumn: series

		annotation SummarizationSetBy = User

	column items
		dataType: int64
		formatString: 0
		lineageTag: 00f5e1b4-abd1-6dc0-49d6-bb4edfec8f8d
		summarizeBy: none
		sourceColumn: items

		annotation SummarizationSetBy = User

	column total_units
		dataType: int64
		formatString: 0
		lineageTag: 28213bb0-b881-ac95-ef1e-25864351258d
		summarizeBy: none
		sourceColumn: total_units

		annotation SummarizationSetBy = User

	column share_of_units
		dataType: double
		formatString: 0.0%
		lineageTag: fbb24916-d926-10be-b712-41e72307aa31
		summarizeBy: none
		sourceColumn: share_of_units

		annotation SummarizationSetBy = User

	column zero_share_after_launch
		dataType: double
		formatString: 0.0%
		lineageTag: 3cb7c9b2-9851-f5c9-801e-f5881d8304bb
		summarizeBy: none
		sourceColumn: zero_share_after_launch

		annotation SummarizationSetBy = User

	column avg_units_per_series_day
		dataType: double
		formatString: #,0.0
		lineageTag: 825d499f-cc61-f3ed-0c15-1b98cd5a18b8
		summarizeBy: none
		sourceColumn: avg_units_per_series_day

		annotation SummarizationSetBy = User

	partition CtxDept = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "CtxDept.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, {"series", "items", "total_units", "share_of_units", "zero_share_after_launch", "avg_units_per_series_day"}),
				    Typed = Table.TransformColumnTypes(Blanks, {{"cat_id", type text}, {"dept_id", type text}, {"series", Int64.Type}, {"items", Int64.Type}, {"total_units", Int64.Type}, {"share_of_units", type number}, {"zero_share_after_launch", type number}, {"avg_units_per_series_day", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

