table CtxEvents
	lineageTag: e56eea61-30b7-4946-b293-469585030d0b

	measure 'Event-day difference' = AVERAGE(CtxEvents[lift_vs_nearby_same_weekday])
		formatString: +0%;-0%
		lineageTag: 5e58febd-6472-307f-78b1-363ca788ee3f

	column event
		dataType: string
		lineageTag: 16b47a2a-6627-2b9e-cf45-3e36536f64b1
		summarizeBy: none
		sourceColumn: event

		annotation SummarizationSetBy = User

	column event_type
		dataType: string
		lineageTag: 6c66d55a-3ace-c63d-3d34-ce70eaba2e10
		summarizeBy: none
		sourceColumn: event_type

		annotation SummarizationSetBy = User

	column occurrences
		dataType: int64
		formatString: 0
		lineageTag: 19f5eb80-0daf-850b-d583-ca22b529862d
		summarizeBy: none
		sourceColumn: occurrences

		annotation SummarizationSetBy = User

	column avg_units_on_event_day
		dataType: double
		formatString: #,0.0
		lineageTag: de34e552-f172-97cb-691e-5d2bc27249af
		summarizeBy: none
		sourceColumn: avg_units_on_event_day

		annotation SummarizationSetBy = User

	column avg_units_same_weekday_nearby
		dataType: double
		formatString: #,0.0
		lineageTag: 6e248f92-d0c7-1714-5aab-b26683ed7b44
		summarizeBy: none
		sourceColumn: avg_units_same_weekday_nearby

		annotation SummarizationSetBy = User

	column lift_vs_nearby_same_weekday
		dataType: double
		formatString: 0.0%
		lineageTag: 0c2d5fd4-64c5-dba2-6875-8bfc56fd13e4
		summarizeBy: none
		sourceColumn: lift_vs_nearby_same_weekday

		annotation SummarizationSetBy = User

	partition CtxEvents = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "CtxEvents.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, {"occurrences", "avg_units_on_event_day", "avg_units_same_weekday_nearby", "lift_vs_nearby_same_weekday"}),
				    Typed = Table.TransformColumnTypes(Blanks, {{"event", type text}, {"event_type", type text}, {"occurrences", Int64.Type}, {"avg_units_on_event_day", type number}, {"avg_units_same_weekday_nearby", type number}, {"lift_vs_nearby_same_weekday", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

