table CtxMonthly
	lineageTag: 4f095004-3fdd-5418-4a9a-4347f5860b91

	measure 'Avg daily units' = SUM(CtxMonthly[avg_daily_units])
		formatString: #,0
		lineageTag: 0fd4f766-566b-778e-f15c-049575ec84ff

	column year
		dataType: int64
		formatString: 0
		lineageTag: 95285e66-559b-a170-b22f-168f4d56c3f9
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = User

	column month
		dataType: int64
		formatString: 0
		lineageTag: d307efc3-0a3e-eabb-dcd6-d4e2af14ad69
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = User

	column month_start
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: f183a3ba-ecd2-b204-17c5-00505470179e
		summarizeBy: none
		sourceColumn: month_start

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

	column state_id
		dataType: string
		lineageTag: 6d564f7d-e95e-77c2-288d-d8afb5fd53fe
		summarizeBy: none
		sourceColumn: state_id

		annotation SummarizationSetBy = User

	column cat_id
		dataType: string
		lineageTag: 08c3953d-1079-de41-a43f-f963ea84e5d8
		summarizeBy: none
		sourceColumn: cat_id

		annotation SummarizationSetBy = User

	column avg_daily_units
		dataType: double
		formatString: #,0.0
		lineageTag: a6b79969-4556-1a18-1440-5ee4f327ccb3
		summarizeBy: none
		sourceColumn: avg_daily_units

		annotation SummarizationSetBy = User

	partition CtxMonthly = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "CtxMonthly.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, {"year", "month", "month_start", "avg_daily_units"}),
				    Typed = Table.TransformColumnTypes(Blanks, {{"year", Int64.Type}, {"month", Int64.Type}, {"month_start", type date}, {"state_id", type text}, {"cat_id", type text}, {"avg_daily_units", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

