table CtxPareto
	lineageTag: a32d8557-f8dd-57d5-8f0d-6c722d1bf6e4

	measure 'Cumulative share of units' = MAX(CtxPareto[cum_share])
		formatString: 0%
		lineageTag: 256c8e57-8c8b-cdd1-1edc-2f7a71fcdd2d

	column rnk
		dataType: int64
		formatString: 0
		lineageTag: 9251e31b-28a0-2c71-8143-69d98b03dcfe
		summarizeBy: none
		sourceColumn: rnk

		annotation SummarizationSetBy = User

	column pct_of_series
		dataType: double
		formatString: #,0.0
		lineageTag: c2e1e450-ae92-c722-08b7-8c8f300db241
		summarizeBy: none
		sourceColumn: pct_of_series

		annotation SummarizationSetBy = User

	column cum_share
		dataType: double
		formatString: 0.0%
		lineageTag: a20df188-0be3-7058-e5b7-08be98421f8a
		summarizeBy: none
		sourceColumn: cum_share

		annotation SummarizationSetBy = User

	partition CtxPareto = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "CtxPareto.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, {"rnk", "pct_of_series", "cum_share"}),
				    Typed = Table.TransformColumnTypes(Blanks, {{"rnk", Int64.Type}, {"pct_of_series", type number}, {"cum_share", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

