table CtxSnap
	lineageTag: 58d9e44a-a6c3-6ffc-1a37-42e595caedee

	measure 'SNAP-day difference' = AVERAGE(CtxSnap[snap_uplift_association])
		formatString: +0.0%;-0.0%
		lineageTag: 0d3434fc-975d-99c4-7904-7a4930438450

	column state_id
		dataType: string
		lineageTag: 996b9f13-21e2-e289-4286-8634b060ecf5
		summarizeBy: none
		sourceColumn: state_id

		annotation SummarizationSetBy = User

	column cat_id
		dataType: string
		lineageTag: 866809f2-84d9-d229-6267-b4333cb06437
		summarizeBy: none
		sourceColumn: cat_id

		annotation SummarizationSetBy = User

	column avg_daily_units_snap
		dataType: double
		formatString: #,0.0
		lineageTag: cf397af5-cea0-34b2-90e3-c29de662e9fb
		summarizeBy: none
		sourceColumn: avg_daily_units_snap

		annotation SummarizationSetBy = User

	column avg_daily_units_non_snap
		dataType: double
		formatString: #,0.0
		lineageTag: a66f4566-4455-9818-889d-816b6abd7dfb
		summarizeBy: none
		sourceColumn: avg_daily_units_non_snap

		annotation SummarizationSetBy = User

	column snap_uplift_association
		dataType: double
		formatString: 0.0%
		lineageTag: 473066e8-f973-e1af-41aa-e2b9adf1c946
		summarizeBy: none
		sourceColumn: snap_uplift_association

		annotation SummarizationSetBy = User

	column snap_days
		dataType: int64
		formatString: 0
		lineageTag: cb24bb11-e144-5e6c-830f-99a4f78a2aeb
		summarizeBy: none
		sourceColumn: snap_days

		annotation SummarizationSetBy = User

	partition CtxSnap = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "CtxSnap.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, {"avg_daily_units_snap", "avg_daily_units_non_snap", "snap_uplift_association", "snap_days"}),
				    Typed = Table.TransformColumnTypes(Blanks, {{"state_id", type text}, {"cat_id", type text}, {"avg_daily_units_snap", type number}, {"avg_daily_units_non_snap", type number}, {"snap_uplift_association", type number}, {"snap_days", Int64.Type}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

