table CtxWeekday
	lineageTag: de9a939b-a293-09b8-b6a5-02fd96645c78

	measure 'Weekday index (avg 100)' = AVERAGE(CtxWeekday[index_vs_week])
		formatString: 0
		lineageTag: b7b46203-d400-dc43-11a6-b06b2cdf668f

	column weekday
		dataType: string
		lineageTag: d2e0d19c-61a2-31ac-f1c4-e984b76a1293
		summarizeBy: none
		sourceColumn: weekday
		sortByColumn: wday

		annotation SummarizationSetBy = User

	column wday
		dataType: int64
		formatString: 0
		lineageTag: 7e769cce-54a1-1f3d-34a5-359f868f8111
		summarizeBy: none
		sourceColumn: wday

		annotation SummarizationSetBy = User

	column state_id
		dataType: string
		lineageTag: e901146c-2e1a-f709-8069-c441e7478f9e
		summarizeBy: none
		sourceColumn: state_id

		annotation SummarizationSetBy = User

	column cat_id
		dataType: string
		lineageTag: 0030eeca-3e2e-58e6-ab5f-7c0130389b5e
		summarizeBy: none
		sourceColumn: cat_id

		annotation SummarizationSetBy = User

	column avg_daily_units
		dataType: double
		formatString: #,0.0
		lineageTag: 740041c5-6367-c508-d6c1-8ea7b8e84543
		summarizeBy: none
		sourceColumn: avg_daily_units

		annotation SummarizationSetBy = User

	column index_vs_week
		dataType: double
		formatString: #,0.0
		lineageTag: a89886d8-d831-81b0-b3c8-ef060c8f1911
		summarizeBy: none
		sourceColumn: index_vs_week

		annotation SummarizationSetBy = User

	partition CtxWeekday = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "CtxWeekday.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, {"wday", "avg_daily_units", "index_vs_week"}),
				    Typed = Table.TransformColumnTypes(Blanks, {{"weekday", type text}, {"wday", Int64.Type}, {"state_id", type text}, {"cat_id", type text}, {"avg_daily_units", type number}, {"index_vs_week", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

