table DataChecks
	lineageTag: ef414b88-faf6-779d-e7e4-c55854c727b2

	measure 'Checks passed' = COUNTROWS(FILTER(DataChecks, DataChecks[pass] = "Yes"))
		formatString: 0
		lineageTag: c20318e7-402a-95d7-1814-471b566f0062

	measure 'Checks run' = COUNTROWS(DataChecks)
		formatString: 0
		lineageTag: 9292da24-ad1c-0aec-df1b-d9364c90ec4e

	column check
		dataType: string
		lineageTag: 2ff16826-b353-97aa-db98-214785a0d135
		summarizeBy: none
		sourceColumn: check

		annotation SummarizationSetBy = User

	column observed
		dataType: int64
		formatString: 0
		lineageTag: 04e2369f-8217-ac38-30e9-209e9dac5494
		summarizeBy: none
		sourceColumn: observed

		annotation SummarizationSetBy = User

	column expected
		dataType: int64
		formatString: 0
		lineageTag: 14fdf2ac-f6fc-9ab3-192d-df57e62cd684
		summarizeBy: none
		sourceColumn: expected

		annotation SummarizationSetBy = User

	column pass
		dataType: string
		lineageTag: fea29fe2-b119-8801-d0d3-c2bfc1e90fad
		summarizeBy: none
		sourceColumn: pass

		annotation SummarizationSetBy = User

	partition DataChecks = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "DataChecks.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, {"observed", "expected"}),
				    Typed = Table.TransformColumnTypes(Blanks, {{"check", type text}, {"observed", Int64.Type}, {"expected", Int64.Type}, {"pass", type text}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

