table ReviewList
	lineageTag: dd9312b8-8d8e-ae29-b525-c14f6de010fa

	measure 'Review score' = SUM(ReviewList[score])
		formatString: 0.00
		lineageTag: 57a9454e-d594-efa7-8ea2-7eb365260f31

	measure 'Recent error (units/wk)' = SUM(ReviewList[recent_error])
		formatString: #,0
		lineageTag: 9d369209-97a6-5ffc-08dc-542ccaaaba1f

	measure 'Range width (units/7d)' = SUM(ReviewList[uncertainty])
		formatString: #,0
		lineageTag: 9bac697b-6e42-0c5c-77cc-d124e3000bbd

	column origin
		dataType: int64
		formatString: 0
		lineageTag: a1f11c23-32d5-2065-c202-2b911a7344ef
		summarizeBy: none
		sourceColumn: origin

		annotation SummarizationSetBy = User

	column period
		dataType: string
		lineageTag: 68c0d094-760e-4253-7b2a-be4df190dfb7
		summarizeBy: none
		sourceColumn: period

		annotation SummarizationSetBy = User

	column rank
		dataType: int64
		formatString: 0
		lineageTag: a90e47fe-b751-d2b3-5d5f-cd9810d709d2
		summarizeBy: none
		sourceColumn: rank

		annotation SummarizationSetBy = User

	column rank_volume
		dataType: double
		formatString: #,0.0
		lineageTag: 230d8c72-dee5-dcb1-0526-f550bd1a0890
		summarizeBy: none
		sourceColumn: rank_volume

		annotation SummarizationSetBy = User

	column rank_recent_error
		dataType: double
		formatString: #,0.0
		lineageTag: e00023a5-8a21-46a4-3abe-5ed98931fb12
		summarizeBy: none
		sourceColumn: rank_recent_error

		annotation SummarizationSetBy = User

	column idx
		dataType: int64
		formatString: 0
		lineageTag: 5a24604a-8673-1ff7-e815-a348a1bf93c0
		summarizeBy: none
		sourceColumn: idx

		annotation SummarizationSetBy = User

	column id
		dataType: string
		lineageTag: b28e0ea8-5f5e-540f-5fce-a3466ceb32af
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = User

	column store_id
		dataType: string
		lineageTag: c4d29372-dee9-11c7-7e1a-3be0f11da3cc
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = User

	column score
		dataType: double
		formatString: #,0.0
		lineageTag: 77cc4ee7-e57f-0fda-e5cb-0e7a05d04a54
		summarizeBy: none
		sourceColumn: score

		annotation SummarizationSetBy = User

	column recent_error
		dataType: double
		formatString: #,0.0
		lineageTag: 67b419be-38bb-f56c-46ce-fca6c2825368
		summarizeBy: none
		sourceColumn: recent_error

		annotation SummarizationSetBy = User

	column bias_signed
		dataType: double
		formatString: #,0.0
		lineageTag: 5113bf0b-03d3-72ef-9d39-0ba9265a4228
		summarizeBy: none
		sourceColumn: bias_signed

		annotation SummarizationSetBy = User

	column uncertainty
		dataType: double
		formatString: #,0.0
		lineageTag: a502707e-76cd-fad6-be62-47d5fb38c24d
		summarizeBy: none
		sourceColumn: uncertainty

		annotation SummarizationSetBy = User

	column volume
		dataType: double
		formatString: #,0.0
		lineageTag: 941ad223-cb4f-6241-ce51-dd0206a06338
		summarizeBy: none
		sourceColumn: volume

		annotation SummarizationSetBy = User

	column forecast_next7
		dataType: double
		formatString: #,0.0
		lineageTag: 30d222be-08c7-f21c-e0ca-bc260f73e022
		summarizeBy: none
		sourceColumn: forecast_next7

		annotation SummarizationSetBy = User

	column price_chg4
		dataType: double
		formatString: 0.0%
		lineageTag: e730b6cb-535c-0098-00be-19040aaa4640
		summarizeBy: none
		sourceColumn: price_chg4

		annotation SummarizationSetBy = User

	column sales_ratio_7_28
		dataType: double
		formatString: #,0.0
		lineageTag: d2fcf012-c569-dc7c-d46b-055174224fb4
		summarizeBy: none
		sourceColumn: sales_ratio_7_28

		annotation SummarizationSetBy = User

	column days_since_sale
		dataType: int64
		formatString: 0
		lineageTag: 666876dd-d596-40ff-7fe5-4b6447ff93b9
		summarizeBy: none
		sourceColumn: days_since_sale

		annotation SummarizationSetBy = User

	column suggested_investigation
		dataType: string
		lineageTag: c5289d25-c4d0-c496-8b36-6513bb6d6dd1
		summarizeBy: none
		sourceColumn: suggested_investigation

		annotation SummarizationSetBy = User

	column outcome_ae
		dataType: double
		formatString: #,0.0
		lineageTag: 491e79e6-1aa1-c8a8-09b5-88af85c5ac49
		summarizeBy: none
		sourceColumn: outcome_ae

		annotation SummarizationSetBy = User

	column outcome_signed
		dataType: double
		formatString: #,0.0
		lineageTag: f790e882-fe09-d7fb-9904-719f0fedc050
		summarizeBy: none
		sourceColumn: outcome_signed

		annotation SummarizationSetBy = User

	column outcome_ne
		dataType: double
		formatString: #,0.0
		lineageTag: 3adcd3e1-eb57-3fc9-8dcf-df3334c897d7
		summarizeBy: none
		sourceColumn: outcome_ne

		annotation SummarizationSetBy = User

	column event
		dataType: string
		lineageTag: 9727b4b8-1192-ad42-a5e3-e15f3560417e
		summarizeBy: none
		sourceColumn: event

		annotation SummarizationSetBy = User

	column top10
		dataType: string
		lineageTag: 3dd397f4-cbcb-e95a-38c1-bfff6de96110
		summarizeBy: none
		sourceColumn: top10

		annotation SummarizationSetBy = User

	column series_label
		dataType: string
		lineageTag: 651ad119-0f7c-5cb3-3ef4-5d37a0b62588
		summarizeBy: none
		sourceColumn: series_label

		annotation SummarizationSetBy = User

	partition ReviewList = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "ReviewList.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, {"origin", "rank", "rank_volume", "rank_recent_error", "idx", "score", "recent_error", "bias_signed", "uncertainty", "volume", "forecast_next7", "price_chg4", "sales_ratio_7_28", "days_since_sale", "outcome_ae", "outcome_signed", "outcome_ne"}),
				    Typed = Table.TransformColumnTypes(Blanks, {{"origin", Int64.Type}, {"period", type text}, {"rank", Int64.Type}, {"rank_volume", type number}, {"rank_recent_error", type number}, {"idx", Int64.Type}, {"id", type text}, {"store_id", type text}, {"score", type number}, {"recent_error", type number}, {"bias_signed", type number}, {"uncertainty", type number}, {"volume", type number}, {"forecast_next7", type number}, {"price_chg4", type number}, {"sales_ratio_7_28", type number}, {"days_since_sale", Int64.Type}, {"suggested_investigation", type text}, {"outcome_ae", type number}, {"outcome_signed", type number}, {"outcome_ne", type number}, {"event", type text}, {"top10", type text}, {"series_label", type text}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

