table SalesHistory
	lineageTag: b6bc75ff-fc50-7e5f-b5cf-6aa46b978530

	measure 'Units sold' = VAR o = SELECTEDVALUE(AsOf[origin]) VAR dd = MAX(Dates[d]) RETURN IF(NOT ISBLANK(o) && HASONEVALUE(Series[idx]) && dd > o - 56 && dd <= o + 28 && dd <= 1941, SUM(SalesHistory[units]) + 0)
		formatString: #,0
		lineageTag: 15b5b554-1353-d882-6694-35614c8ae983

	column idx
		dataType: int64
		formatString: 0
		lineageTag: ca3a2e60-2261-00ff-01ff-3a7b3754c8af
		summarizeBy: none
		sourceColumn: idx

		annotation SummarizationSetBy = User

	column d
		dataType: int64
		formatString: 0
		lineageTag: 644b0b09-57fc-7a82-9e2d-1bd6375f23c9
		summarizeBy: none
		sourceColumn: d

		annotation SummarizationSetBy = User

	column units
		dataType: double
		formatString: #,0.0
		lineageTag: b88b33b2-8f98-cc04-eebf-9c7294e41861
		summarizeBy: none
		sourceColumn: units

		annotation SummarizationSetBy = User

	partition SalesHistory = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "SalesHistory.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, {"idx", "d", "units"}),
				    Typed = Table.TransformColumnTypes(Blanks, {{"idx", Int64.Type}, {"d", Int64.Type}, {"units", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

