table Strata
	lineageTag: 889ac453-9f30-0067-3086-38fa85af25cf

	measure 'Series in stratum' = SUM(Strata[series])
		formatString: 0
		lineageTag: 2533622a-1010-5076-280e-1f8d18d5eace

	column store_stratum
		dataType: string
		lineageTag: 50477333-48c5-c38c-ad06-fcdaa75e8d22
		summarizeBy: none
		sourceColumn: store_stratum

		annotation SummarizationSetBy = User

	column series
		dataType: int64
		formatString: 0
		lineageTag: 9d0b0675-dc06-0252-3b3d-9256bf3e930c
		summarizeBy: none
		sourceColumn: series

		annotation SummarizationSetBy = User

	partition Strata = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "Strata.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, {"series"}),
				    Typed = Table.TransformColumnTypes(Blanks, {{"store_stratum", type text}, {"series", Int64.Type}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

